parameters:
#    rest_api_crud.example.class: Onema\BaseApiBundle\Example

services:
#    rest_api_crud.example:
#        class: %rest_api_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
