parameters:
#    base_api.example.class: Onema\BaseApiBundle\Example

services:
#    base_api.example:
#        class: %base_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
